name: Auto Merge Main into Dev

on:
  push:
    branches:
      - main

jobs:
  merge-main-to-dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set Git username and email
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Fetch all branches
        run: git fetch --all

      - name: Switch to dev branch and merge main
        run: |
          git checkout dev
          git merge main --no-ff -m "Auto merge main into dev"
      
      - name: Push changes to dev
        run: git push origin dev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}