name: Build and Push Dev Docker Image

on:
  push:
    branches:
      - dev
    paths-ignore:
      - 'README.MD'
      - 'docker-compose.yml'
      - '.github/**'
      - 'vercel.json'
      - '.gitignore'
      
jobs:
  build-and-push-dev:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: dev

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push dev Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          iidamie/deepseek2api:latest-dev
        platforms: linux/amd64,linux/arm64
        build-args: TARGETPLATFORM=${{ matrix.platform }}